#ifdef OSCILLOSCOPE_DEBUG
#define OSCILLOSCOPE_DEBUG_INIT() pinMode(10,OUTPUT); digitalWrite(10,LOW);
#define OSCILLOSCOPE_DEBUG_PULSE() PINB=0b01000000;
#define OSCILLOSCOPE_DEBUG_END() digitalWrite(10,LOW); pinMode(10,INPUT);
#else
#define OSCILLOSCOPE_DEBUG_INIT()
#define OSCILLOSCOPE_DEBUG_PULSE()
#define OSCILLOSCOPE_DEBUG_END()
#endif
