FROM ubuntu:22.04

LABEL maintainer="moults31@gmail.com"
LABEL version="0.1"
LABEL description="This image provides build dependencies for OpenLDAT, including the Arduino firmware and the java app"

ARG DEBIAN_FRONTEND=noninteractive

ARG USERNAME=openldat-dev
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create a non-root user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Install any apt packages needed
RUN apt-get update && apt-get install --no-install-recommends -y \
    # Base
    sudo \
    nano \
    curl \
    dumb-init \
    gosu \
    libssl-dev \
    ca-certificates \
    unzip \
    git \
    zsh \
    # For serial monitor
    picocom \
    # For flashing firmware to Elite C
    dfu-programmer \
    # Cleanup
    && apt-get autoremove -y \
    && apt-get clean \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* \
    && update-ca-certificates


# Add the entrypoint script and make it executable
ADD ./entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Install arduino cli
RUN curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh

# Switch to the user now
RUN chsh -s /usr/bin/zsh $USERNAME
USER $USERNAME
WORKDIR '/openldat'
ENV USER=${USERNAME}

# Add zsh + oh-my-zsh to spruce things up
RUN git clone https://github.com/moults31/.dots.git /home/$USERNAME/.dots
RUN cd /home/$USERNAME/.dots && ./init.sh && cd -

# Add Sparkfun URL to get access to Pro Micro and Elite C board configs
RUN /usr/local/bin/arduino-cli config init --additional-urls https://raw.githubusercontent.com/sparkfun/Arduino_Boards/main/IDE_Board_Manager/package_sparkfun_index.json
RUN /usr/local/bin/arduino-cli core update-index
RUN /usr/local/bin/arduino-cli core install sparkfun:avr
RUN /usr/local/bin/arduino-cli core install arduino:avr

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]