services:
  openldat:
    image: openldat:latest
    container_name: openldat
    command: zsh
    build: .
    privileged: true
    network_mode: "host"
    volumes:
      - "..:/openldat"
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - DISPLAY=$DISPLAY